//! Integration tests for enrichment passes.
//!
//! These tests exercise the public `run_*_enrichment` entry points through
//! realistic filesystem setups, verifying gate logic, incremental cache
//! behaviour, and error handling without requiring external binaries (node,
//! pyright, cargo nightly) to be installed.
//!
//! Companion to the unit tests that live inside each enrichment module and can
//! call private helpers directly.  Tests here use only the public cs-core API.

use cs_core::db::Database;
use cs_core::pyright_enrich::run_pyright_enrichment;
use cs_core::rustdoc_enrich::run_rustdoc_enrichment;
use cs_core::ts_enrich::run_ts_enrichment;
use cs_core::watcher::hash_content;

// ── TypeScript enrichment ─────────────────────────────────────────────────────

/// When tsconfig.json exists and its hash is already in the DB cache, the TS
/// enrichment pass must return 0 without invoking `node`.  This test is fully
/// deterministic — it does not require Node.js to be installed.
#[test]
fn ts_cache_hit_bypasses_node() {
    let dir = tempfile::tempdir().unwrap();
    let db_path = dir.path().join("index.db");
    let db = Database::open(&db_path).expect("db open");

    let tsconfig_content = br#"{"compilerOptions":{}}"#;
    std::fs::write(dir.path().join("tsconfig.json"), tsconfig_content).unwrap();

    // Prime the DB with the hash that run_ts_enrichment computes internally.
    let hash = hash_content(tsconfig_content);
    db.set_macro_expand_hash("__ts_enrich__", &hash).unwrap();

    let count = run_ts_enrichment(dir.path(), &mut [], &db);
    assert_eq!(
        count, 0,
        "cache hit must return 0 regardless of node availability"
    );
}

/// With no tsconfig.json the TS pass must return 0 without writing anything
/// to the DB (so a later run with a tsconfig is not accidentally skipped).
#[test]
fn ts_no_tsconfig_leaves_cache_empty() {
    let dir = tempfile::tempdir().unwrap();
    let db_path = dir.path().join("index.db");
    let db = Database::open(&db_path).expect("db open");

    let count = run_ts_enrichment(dir.path(), &mut [], &db);
    assert_eq!(count, 0);

    // The cache key must not have been written.
    let cached = db.get_macro_expand_hash("__ts_enrich__").expect("db read");
    assert!(
        cached.is_none(),
        "cache must remain empty when tsconfig.json is absent"
    );
}

// ── Rustdoc enrichment ────────────────────────────────────────────────────────

/// When Cargo.lock exists and its hash is already cached, rustdoc enrichment
/// must return 0 without invoking `cargo +nightly doc`.
#[test]
fn rustdoc_cache_hit_bypasses_cargo_doc() {
    let dir = tempfile::tempdir().unwrap();
    let db_path = dir.path().join("index.db");
    let db = Database::open(&db_path).expect("db open");

    std::fs::write(dir.path().join("Cargo.toml"), "[package]\nname=\"x\"\n").unwrap();

    let lock_content = b"# This file is automatically @generated by Cargo.\n";
    std::fs::write(dir.path().join("Cargo.lock"), lock_content).unwrap();

    let lock_hash = hash_content(lock_content);
    db.set_macro_expand_hash("__rustdoc__", &lock_hash).unwrap();

    let count = run_rustdoc_enrichment(dir.path(), &mut [], &db);
    assert_eq!(
        count, 0,
        "cache hit must return 0 regardless of nightly availability"
    );
}

/// Without Cargo.toml the rustdoc pass must gate immediately and not write to
/// the DB cache.
#[test]
fn rustdoc_no_cargo_toml_leaves_cache_empty() {
    let dir = tempfile::tempdir().unwrap();
    let db_path = dir.path().join("index.db");
    let db = Database::open(&db_path).expect("db open");

    let count = run_rustdoc_enrichment(dir.path(), &mut [], &db);
    assert_eq!(count, 0);

    let cached = db.get_macro_expand_hash("__rustdoc__").expect("db read");
    assert!(
        cached.is_none(),
        "cache must remain empty when Cargo.toml is absent"
    );
}

// ── Pyright enrichment ────────────────────────────────────────────────────────

/// Without any Python symbols the pyright pass must return 0 immediately,
/// never reaching the `pyright` binary check.
#[test]
fn pyright_empty_symbols_returns_zero() {
    let dir = tempfile::tempdir().unwrap();
    let db_path = dir.path().join("index.db");
    let db = Database::open(&db_path).expect("db open");

    let count = run_pyright_enrichment(dir.path(), &mut [], &db);
    assert_eq!(count, 0);
}

// ── Cross-enricher smoke test ─────────────────────────────────────────────────

/// All three enrichment passes must accept an empty symbol slice and return 0
/// without panicking, regardless of what is or is not installed.
#[test]
fn all_enrichers_accept_empty_symbol_slice() {
    let dir = tempfile::tempdir().unwrap();
    let db_path = dir.path().join("index.db");
    let db = Database::open(&db_path).expect("db open");

    // Provide the minimal workspace files so we get past gate 1 for each pass.
    std::fs::write(dir.path().join("tsconfig.json"), "{}").unwrap();
    std::fs::write(dir.path().join("Cargo.toml"), "[package]\nname=\"x\"\n").unwrap();

    assert_eq!(run_ts_enrichment(dir.path(), &mut [], &db), 0);
    assert_eq!(run_rustdoc_enrichment(dir.path(), &mut [], &db), 0);
    assert_eq!(run_pyright_enrichment(dir.path(), &mut [], &db), 0);
}
